### ISSUE TITLE
Any plans on "updating" binnie's mods?

### ISSUE THREAD

**Issue by Tomson124** [Chocohead/Binnie-Patcher#28]
As binnie "open sourced" his mod shortly there would be the option to directly update and fix it.
Maybe you have the knowledge and time to do it @Chocohead ?

**Comment by Dream-Master** [comment]
Binne is not coding any line at Extra Bees since 2 years when I am remember right. Why you think he is now open his code?

**Comment by danielrossyamitrano** [comment]
i think I read somewhere that binnie released the code for editing

**Comment by Tomson124** [comment]
@Dream-Master  I know he didn't do anything in the last couple of months but some other modders achieved to get in contact with him and that's the result: https://www.reddit.com/r/feedthebeast/comments/4pgsxh/enjoy_binnies_bees_trees_well_some_good_news_for/

**Comment by Dream-Master** [comment]
Ah ok nice to know.

**Comment by Chocohead** [comment]
I might do at some point, but Binnie's mods were huge and I really don't have time to seriously focus on something that big at the moment with other things that would take priority. Mezz already said he'd work on another version of Extra Bees and merging Extra Trees into Forestry itself, but that hasn't seemed to have moved beyond the idea phase either because he's got other mods to focus on as well (from what I can tell). Maybe one day though.

**Comment by Chocohead** [comment]
All porting work for Binnie's Mods is [here](https://github.com/ForestryMC/Binnie) now.
